In [ ]:
import numpy as np

In [ ]:
B=np.array([[2,1,3],
   [5,3,2],
   [1,4,3]])
np.linalg.det(B)

40.000000000000014

In [ ]:
v=np.array([1,-3,8,4,5])
w=np.array([2,7,10,1,1])

In [ ]:
##ZA Dobit normu mozemo na dva načina
np.math.sqrt(np.inner(v,v))

10.723805294763608

In [ ]:
# ili
np.linalg.norm(v)

10.723805294763608

In [ ]:
## linearna kombinacija vektora
7*v-8*w

array([ -9, -77, -24,  20,  27])

In [ ]:
##linearno zavisni vektor o vektoru v
3*v


array([ 3, -9, 24, 12, 15])

In [ ]:
#kut između ta dva vektora
c=np.inner(v,w)/(np.linalg.norm(v)*np.linalg.norm(w))
c

0.5243041203911968

In [ ]:
c_rad=np.arccos(c) ##kut u radijanima
c_rad

1.0188986293626563

In [ ]:
## za kut u stupnjevima
c_deg=c_rad*180/np.pi
c_deg

58.378591214144535

In [ ]:
#napravimo dvije matrice A i B
A=np.array([[7,0,0],
   [0,8,0],
   [0,0,9]])
B=np.array([[1,2,4],
   [8,9,10],
   [-1,0,3]])

In [ ]:
#Zbroj neke linearne kombinacije
A+2*B

array([[ 9,  4,  8],
       [16, 26, 20],
       [-2,  0, 15]])

In [ ]:
# Racunanje trag matrice
B.trace()

13

In [ ]:
#Transponirana matrica
B.T

array([[ 1,  8, -1],
       [ 2,  9,  0],
       [ 4, 10,  3]])

In [ ]:
#energija matrice je B*Btransponirano pa trag
(B*B.T).trace()

91

In [ ]:
# norma matrice B
np.linalg.norm(B)

16.61324772583615

In [ ]:
#svojstvene vrijednosti matrice A - 7,8,9 jer je dijagonalizirana
# ali da nije bila onda

np.linalg.eig(B)

(array([10.34272932, -0.17093235,  2.82820303]),
 array([[-0.19818835, -0.62274344,  0.08165993],
        [-0.97979225,  0.75737776, -0.87601076],
        [ 0.0269911 , -0.19639127,  0.47532811]]))

In [ ]:
# Nađite vektor koji je okomit na prvi vektor a u ravnini sa oba
# teka
a=np.array([1,2,4])
b=np.array([8,9,10])

x=np.inner(a,b)/np.inner(a,a)*a
x

array([ 3.14285714,  6.28571429, 12.57142857])

In [ ]:
c=b-x
c

array([ 4.85714286,  2.71428571, -2.57142857])

In [ ]:
## Provjerimo jel skalarni 0
np.inner(a,c).round()

0.0

In [ ]:
# Je zato sta je iznos 1,78 * 10^(-15)

In [ ]:
# Možda bude i GranSmidth na 4 vektora


In [ ]:
#racunanje determinante
np.linalg.det(B)

-4.9999999999999964

In [ ]:
#provjeri asocijativnost ili nesto bi isto moglo

In [ ]:
# i na papiru kako neki ekstrem nac

In [ ]:
B=np.array([[2,2,6],
   [1,3,9],
   [6,1,0]])
np.linalg.norm(B)

13.114877048604

In [ ]:
B=np.array([[1,2,3],
   [2,4,6],
   [2,6,9]])
np.linalg.det(B)

0.0

In [ ]:
##ZA Dobit normu mozemo na dva načina

v=np.array([1,-3,8,4,5])
w=np.array([2,7,10,1,1])
np.inner(v,w)

70